version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm run start
    volumes:
      - ./frontend/src:/usr/src/app/src
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src

  auth:
    command: npm run dev
    volumes:
      - ./auth/src:/usr/src/app/src

  mailer:
    command: npm run dev
    volumes:
      - ./mailer/src:/usr/src/app/src

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
